version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 0.27.0-RC1
  - 2.11.12
  - 2.12.12
  - 2.13.3

env:
  - ADOPTOPENJDK=8     SCALAJS_VERSION=
  - ADOPTOPENJDK=8     SCALAJS_VERSION=1.3.0
  - ADOPTOPENJDK=11    SCALAJS_VERSION=

matrix:
  exclude:
    - scala: 0.27.0-RC1
      env: ADOPTOPENJDK=8     SCALAJS_VERSION=1.3.0
  include:
    - scala: 2.11.12
      env: ADOPTOPENJDK=8     SCALANATIVE_VERSION=0.3.9
    - scala: 2.11.12
      env: ADOPTOPENJDK=8     SCALANATIVE_VERSION=0.4.0-M2

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh

notifications:
  email:
    - adriaan.moors@lightbend.com
    - seth.tisue@lightbend.com
